// src/lib/remedyDb.js
// 100-remedy classical homeopathic database.
// Each entry: id, name, abbr, keynotes, affinities, mentals,
//             modalities, constitution, conditions, potency, sensations

export const REMEDY_DB = [
  {
    id: "acon", name: "Aconitum Napellus", abbr: "Acon.",
    keynotes: ["sudden onset", "fright", "fear of death", "intense anxiety", "cold dry wind", "fever", "restlessness"],
    affinities: ["heart", "respiratory", "nervous system", "fever"],
    mentals: ["fear", "panic", "anxiety", "restlessness", "fear of death", "shock"],
    modalities: { better: ["open air", "rest"], worse: ["cold dry wind", "night", "fright", "warm room", "music"] },
    constitution: ["chilly"],
    conditions: ["fever", "cold", "croup", "anxiety", "panic attack", "shock", "influenza", "earache"],
    potency: { acute: "30C every 1-2hrs", chronic: "200C weekly" },
    sensations: ["burning", "tingling", "numbness"],
  },
  {
    id: "apis", name: "Apis Mellifica", abbr: "Apis.",
    keynotes: ["stinging burning pain", "swelling", "edema", "no thirst", "heat aggravates", "jealousy", "busy"],
    affinities: ["skin", "kidneys", "throat", "joints", "ovaries"],
    mentals: ["jealousy", "busy", "fidgety", "irritable", "no thirst"],
    modalities: { better: ["cold", "cold applications", "open air", "uncovering"], worse: ["heat", "hot room", "touch", "pressure", "right side"] },
    constitution: ["hot"],
    conditions: ["allergic reactions", "hives", "insect stings", "urinary tract infection", "sore throat", "joint swelling", "edema", "kidney issues"],
    potency: { acute: "30C every 2hrs", chronic: "200C fortnightly" },
    sensations: ["stinging", "burning", "puffiness"],
  },
  {
    id: "arg-n", name: "Argentum Nitricum", abbr: "Arg-n.",
    keynotes: ["anticipatory anxiety", "hurried", "craves sweets", "fears", "flatulence", "warm blooded"],
    affinities: ["nervous system", "stomach", "mucous membranes", "eyes"],
    mentals: ["anxiety", "anticipation", "hurried", "impulsive", "fear of heights", "fear of crowds", "superstitious"],
    modalities: { better: ["cool air", "cold", "pressure"], worse: ["sweets", "anxiety", "heat", "left side", "night"] },
    constitution: ["hot"],
    conditions: ["anxiety", "exam nerves", "stage fright", "diarrhea", "flatulence", "eye complaints", "headache"],
    potency: { acute: "30C as needed", chronic: "200C monthly" },
    sensations: ["splinter-like", "bloating", "trembling"],
  },
  {
    id: "arn", name: "Arnica Montana", abbr: "Arn.",
    keynotes: ["injury", "trauma", "bruised feeling", "says fine when not", "overexertion", "soreness"],
    affinities: ["muscles", "joints", "head", "heart"],
    mentals: ["says they are fine", "fear of being touched", "indifference", "forgetful after trauma"],
    modalities: { better: ["lying down", "head low"], worse: ["touch", "motion", "cold damp", "injury"] },
    constitution: ["neutral"],
    conditions: ["bruises", "trauma", "surgery recovery", "sports injuries", "overexertion", "jet lag", "concussion"],
    potency: { acute: "30C every 2-4hrs", chronic: "200C as needed" },
    sensations: ["bruised", "sore", "aching"],
  },
  {
    id: "ars", name: "Arsenicum Album", abbr: "Ars.",
    keynotes: ["restlessness", "anxiety", "burning pains better heat", "thirst for sips", "midnight aggravation", "perfectionist", "fastidious"],
    affinities: ["digestive", "respiratory", "skin", "nervous system"],
    mentals: ["anxiety", "restlessness", "fear of death", "perfectionist", "fastidious", "fear of being alone", "miserly"],
    modalities: { better: ["heat", "warm drinks", "company", "sitting up"], worse: ["cold", "midnight", "alone", "exertion"] },
    constitution: ["chilly"],
    conditions: ["food poisoning", "gastroenteritis", "asthma", "anxiety", "skin eruptions", "influenza", "insomnia"],
    potency: { acute: "30C every 2hrs", chronic: "200C fortnightly" },
    sensations: ["burning", "weakness", "restlessness"],
  },
  {
    id: "bell", name: "Belladonna", abbr: "Bell.",
    keynotes: ["sudden violent onset", "heat", "redness", "throbbing", "dilated pupils", "hot skin", "delirium"],
    affinities: ["head", "throat", "nervous system", "fever", "right side"],
    mentals: ["delirium", "violent", "biting", "striking", "sees visions", "fear of animals"],
    modalities: { better: ["semi-erect", "warmth"], worse: ["touch", "jar", "noise", "light", "afternoon", "drafts"] },
    constitution: ["hot"],
    conditions: ["high fever", "headache", "sore throat", "ear infection", "sunstroke", "convulsions", "teething"],
    potency: { acute: "30C every 1-2hrs", chronic: "200C weekly" },
    sensations: ["throbbing", "burning", "flushing"],
  },
  {
    id: "bry", name: "Bryonia Alba", abbr: "Bry.",
    keynotes: ["motion aggravates", "wants to lie still", "thirst for large quantities", "irritable", "dryness", "stitching pains", "wants to go home"],
    affinities: ["mucous membranes", "joints", "respiratory", "digestive", "liver"],
    mentals: ["irritable", "wants to be left alone", "talks of business", "anxiety about finances", "fear of poverty"],
    modalities: { better: ["rest", "pressure", "lying on painful side", "cold things"], worse: ["motion", "warmth", "morning", "eating", "touch"] },
    constitution: ["chilly"],
    conditions: ["arthritis", "pneumonia", "pleurisy", "constipation", "headache", "influenza", "mastitis"],
    potency: { acute: "30C every 2-4hrs", chronic: "200C monthly" },
    sensations: ["stitching", "dryness", "heaviness"],
  },
  {
    id: "calc", name: "Calcarea Carbonica", abbr: "Calc.",
    keynotes: ["slow", "stubborn", "chilly", "sweats on head", "fears", "craves eggs", "fat unhurried"],
    affinities: ["glands", "bones", "skin", "metabolism"],
    mentals: ["slow", "stubborn", "practical", "fear of insanity", "fear of disease", "anxiety", "overwhelmed"],
    modalities: { better: ["dry weather", "lying on painful side"], worse: ["cold damp", "exertion", "full moon", "milk", "left side"] },
    constitution: ["chilly"],
    conditions: ["obesity", "hypothyroidism", "dental problems", "bone issues", "eczema", "anxiety", "polyps", "gallstones"],
    potency: { acute: "30C", chronic: "200C or 1M monthly" },
    sensations: ["heaviness", "coldness in head", "sweating"],
  },
  {
    id: "calc-p", name: "Calcarea Phosphorica", abbr: "Calc-p.",
    keynotes: ["growing pains", "dissatisfied", "craves smoked meat", "cold air aggravates", "teething problems", "anemia"],
    affinities: ["bones", "glands", "blood", "teeth"],
    mentals: ["dissatisfied", "forgetful", "fretful", "wants to travel"],
    modalities: { better: ["summer", "warm weather"], worse: ["cold", "damp", "change of weather", "thinking of complaints"] },
    constitution: ["chilly"],
    conditions: ["growing pains", "bone fractures", "anemia", "dental problems", "headache in school children", "diarrhea"],
    potency: { acute: "6X tissue salt", chronic: "30C weekly" },
    sensations: ["aching", "coldness", "numbness"],
  },
  {
    id: "canth", name: "Cantharis", abbr: "Canth.",
    keynotes: ["burning urination", "cystitis", "rawness", "intense sexual desire", "blistering"],
    affinities: ["urinary", "skin", "sexual organs", "kidneys"],
    mentals: ["rage", "violent sexual desire", "delirium"],
    modalities: { better: ["warmth", "rubbing"], worse: ["urination", "touch", "coffee", "cold water"] },
    constitution: ["hot"],
    conditions: ["cystitis", "urinary tract infection", "burns", "blisters", "kidney inflammation", "sunburn"],
    potency: { acute: "30C every 2hrs", chronic: "200C weekly" },
    sensations: ["burning", "rawness", "scalding"],
  },
  {
    id: "carb-v", name: "Carbo Vegetabilis", abbr: "Carb-v.",
    keynotes: ["flatulence", "bloating", "collapse", "wants to be fanned", "cold but wants air", "sluggish"],
    affinities: ["digestive", "respiratory", "circulation", "venous system"],
    mentals: ["sluggish", "indifferent", "fixed ideas", "fear of dark"],
    modalities: { better: ["fanning", "eructation", "cold air"], worse: ["fatty food", "evening", "warmth", "lying down"] },
    constitution: ["chilly"],
    conditions: ["flatulence", "indigestion", "collapse", "varicose veins", "asthma", "hangover", "old age debility"],
    potency: { acute: "30C every 2hrs", chronic: "200C monthly" },
    sensations: ["bloating", "heaviness", "coldness"],
  },
  {
    id: "caust", name: "Causticum", abbr: "Caust.",
    keynotes: ["paralysis", "sympathetic", "champion of underdogs", "warts", "bedwetting", "hoarseness", "rawness"],
    affinities: ["nervous system", "urinary", "vocal cords", "tendons"],
    mentals: ["sympathetic", "anxious about others", "rebellious", "weeping at injustice", "pessimistic"],
    modalities: { better: ["damp weather", "warmth", "cold drinks"], worse: ["clear cold weather", "dry cold wind", "drafts", "motion"] },
    constitution: ["chilly"],
    conditions: ["paralysis", "palsy", "warts", "enuresis", "hoarseness", "burns old", "arthritis", "ptosis"],
    potency: { acute: "30C", chronic: "200C fortnightly" },
    sensations: ["rawness", "burning", "paralytic weakness"],
  },
  {
    id: "cham", name: "Chamomilla", abbr: "Cham.",
    keynotes: ["oversensitive to pain", "nothing pleases", "demands then rejects", "one cheek red one pale", "teething", "cross"],
    affinities: ["nervous system", "digestive", "dentition", "ears"],
    mentals: ["angry", "oversensitive", "impossible to please", "capricious", "impatient"],
    modalities: { better: ["being carried", "warm wet weather", "fasting"], worse: ["heat", "teething", "anger", "cold wind", "night"] },
    constitution: ["hot"],
    conditions: ["teething", "colic", "ear pain", "toothache", "insomnia from pain", "diarrhea in teething"],
    potency: { acute: "30C every 2hrs", chronic: "200C weekly" },
    sensations: ["unbearable pain", "sensitivity", "irritability"],
  },
  {
    id: "chin", name: "China Officinalis", abbr: "Chin.",
    keynotes: ["weakness from fluid loss", "periodic complaints", "bloating", "debility", "sensitive to touch but pressure better"],
    affinities: ["blood", "liver", "spleen", "nervous system"],
    mentals: ["apathetic", "theorizing", "indifference", "sensitive", "hypersensitive touch"],
    modalities: { better: ["hard pressure", "warmth", "loose clothes"], worse: ["slight touch", "drafts", "every other day", "loss of fluids"] },
    constitution: ["chilly"],
    conditions: ["debility after illness", "anemia", "malaria-type fevers", "flatulence", "hemorrhage effects", "neuralgia"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["weakness", "bloating", "periodicity"],
  },
  {
    id: "cocc", name: "Cocculus Indicus", abbr: "Cocc.",
    keynotes: ["motion sickness", "dizziness", "exhaustion from nursing", "hollow feeling", "time passes quickly"],
    affinities: ["nervous system", "cerebellum", "digestive"],
    mentals: ["slow to answer", "cannot bear contradiction", "grief from nursing", "time distorted"],
    modalities: { better: ["lying", "quiet", "warmth"], worse: ["motion", "noise", "tobacco", "loss of sleep"] },
    constitution: ["chilly"],
    conditions: ["motion sickness", "travel sickness", "vertigo", "jet lag", "caregiver exhaustion", "insomnia"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["hollow", "dizzy", "empty"],
  },
  {
    id: "coff", name: "Coffea Cruda", abbr: "Coff.",
    keynotes: ["oversensitivity", "sleeplessness from joy or pain", "hyperactive mind", "pain feels unbearable", "overexcitement"],
    affinities: ["nervous system", "mind", "sleep"],
    mentals: ["overactive mind", "cannot switch off", "overjoy", "hypersensitive", "tearful from joy"],
    modalities: { better: ["warmth", "ice", "lying still"], worse: ["noise", "touch", "smell", "open air", "cold"] },
    constitution: ["chilly"],
    conditions: ["insomnia", "toothache", "headache", "palpitations", "neuralgia", "overstimulation"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["unbearable", "tingling", "over-alertness"],
  },
  {
    id: "coloc", name: "Colocynthis", abbr: "Coloc.",
    keynotes: ["cramping colic better pressure", "anger before complaints", "doubles over with pain", "irritable"],
    affinities: ["digestive", "nervous system", "joints"],
    mentals: ["anger", "indignation", "humiliation", "impatient"],
    modalities: { better: ["hard pressure", "warmth", "doubling up", "coffee"], worse: ["anger", "indignation", "eating", "damp cold"] },
    constitution: ["chilly"],
    conditions: ["colic", "diarrhea after anger", "sciatica", "ovarian cysts", "kidney stones", "neuralgia"],
    potency: { acute: "30C every 30min", chronic: "200C weekly" },
    sensations: ["cramping", "cutting", "boring"],
  },
  {
    id: "cup-m", name: "Cuprum Metallicum", abbr: "Cup.",
    keynotes: ["cramps", "spasms", "convulsions", "blue face", "beginning in fingers toes"],
    affinities: ["muscles", "nervous system", "respiratory"],
    mentals: ["malicious", "obstinate", "morose", "secretive"],
    modalities: { better: ["cold drinks", "pressure"], worse: ["touch", "night", "vomiting"] },
    constitution: ["chilly"],
    conditions: ["epilepsy", "cramps", "whooping cough", "cholera", "spasms"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["cramping", "spasm", "constriction"],
  },
  {
    id: "dros", name: "Drosera Rotundifolia", abbr: "Dros.",
    keynotes: ["spasmodic cough", "whooping cough", "deep hoarse cough", "holds chest during cough", "midnight cough"],
    affinities: ["respiratory", "larynx"],
    mentals: ["persistent", "suspicious", "restless"],
    modalities: { better: ["open air", "walking", "pressure"], worse: ["lying down", "after midnight", "warmth", "laughing"] },
    constitution: ["chilly"],
    conditions: ["whooping cough", "croup", "asthma", "laryngitis", "bronchitis"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["tickling", "spasm", "choking"],
  },
  {
    id: "euphr", name: "Euphrasia Officinalis", abbr: "Euphr.",
    keynotes: ["eye symptoms predominant", "burning acrid eye discharge", "bland nasal discharge", "photophobia"],
    affinities: ["eyes", "mucous membranes"],
    mentals: ["none distinctive"],
    modalities: { better: ["dark room", "coffee"], worse: ["light", "wind", "warmth"] },
    constitution: ["neutral"],
    conditions: ["conjunctivitis", "hay fever with eye symptoms", "measles", "iritis", "blepharitis"],
    potency: { acute: "30C every 2hrs", chronic: "6C locally" },
    sensations: ["burning eyes", "photophobia", "lacrimation"],
  },
  {
    id: "ferr-p", name: "Ferrum Phosphoricum", abbr: "Ferr-p.",
    keynotes: ["first stage inflammation", "slow onset fever", "anemia", "flush alternating pale", "nosebleed"],
    affinities: ["blood vessels", "lungs", "fever"],
    mentals: ["talkative", "excitable"],
    modalities: { better: ["cold applications"], worse: ["right side", "4-6am", "motion", "jarring"] },
    constitution: ["neutral"],
    conditions: ["early fever", "ear infection early stage", "cold beginning", "anemia", "nosebleed"],
    potency: { acute: "6X tissue salt or 30C", chronic: "200C" },
    sensations: ["throbbing", "congestion"],
  },
  {
    id: "gels", name: "Gelsemium Sempervirens", abbr: "Gels.",
    keynotes: ["weakness", "drooping eyelids", "trembling", "anticipation anxiety", "no thirst with fever", "dull heavy"],
    affinities: ["nervous system", "muscles", "motor nerves", "fever"],
    mentals: ["anticipatory dread", "cowardice", "dullness", "wants to be left alone", "fear of dentist"],
    modalities: { better: ["urination", "alcohol", "sweating", "movement"], worse: ["damp", "excitement", "bad news", "spring"] },
    constitution: ["neutral"],
    conditions: ["influenza", "exam anxiety", "stage fright", "headache", "neurological complaints", "vertigo"],
    potency: { acute: "30C every 2-4hrs", chronic: "200C weekly" },
    sensations: ["heaviness", "trembling", "weakness"],
  },
  {
    id: "graph", name: "Graphites", abbr: "Graph.",
    keynotes: ["unhealthy skin", "honey-like discharge", "fissures", "obesity", "chilly", "hesitant", "weeps at music"],
    affinities: ["skin", "mucous membranes", "glands", "nails"],
    mentals: ["cautious", "indecisive", "weeps at music", "anxious", "depressed"],
    modalities: { better: ["wrapping up", "dark", "rest"], worse: ["cold", "damp", "left side", "morning", "night"] },
    constitution: ["chilly"],
    conditions: ["eczema", "psoriasis", "cracks skin", "constipation", "obesity", "nail problems", "keloid scars"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["rawness", "itching", "burning"],
  },
  {
    id: "hep", name: "Hepar Sulphuris", abbr: "Hep.",
    keynotes: ["oversensitive to pain", "splinter sensation", "offensive discharges", "chilly", "unhealthy suppurating skin", "irritable"],
    affinities: ["skin", "glands", "respiratory", "throat"],
    mentals: ["irritable", "hasty", "violent impulses", "sensitive to impressions"],
    modalities: { better: ["warmth", "wrapping", "damp weather"], worse: ["cold", "slightest draft", "touch", "noise", "dry cold"] },
    constitution: ["chilly"],
    conditions: ["abscess", "sore throat suppurating", "croup", "skin infections", "sinusitis", "ear infections pus"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["splinter-like", "stinging", "offensive"],
  },
  {
    id: "hyos", name: "Hyoscyamus Niger", abbr: "Hyos.",
    keynotes: ["jealousy", "shamelessness", "suspicion", "delirium", "twitching", "mania"],
    affinities: ["nervous system", "mind", "muscles"],
    mentals: ["jealous", "suspicious", "obscene", "lascivious", "delirium", "mania", "paranoia"],
    modalities: { better: ["stooping", "warmth"], worse: ["emotional excitement", "jealousy", "cold"] },
    constitution: ["hot"],
    conditions: ["mania", "delirium", "jealousy", "epilepsy", "twitching", "insomnia from suspicious thoughts"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["twitching", "spasm", "mania"],
  },
  {
    id: "ign", name: "Ignatia Amara", abbr: "Ign.",
    keynotes: ["grief", "contradictions", "sighing", "lump in throat", "hysteria", "never two the same", "silent grief"],
    affinities: ["nervous system", "emotional sphere", "digestive"],
    mentals: ["grief", "disappointment", "silent suffering", "mood swings", "contradictory symptoms", "sighing"],
    modalities: { better: ["eating", "change of position", "hard pressure", "warmth"], worse: ["coffee", "tobacco", "grief", "emotional shock"] },
    constitution: ["neutral"],
    conditions: ["grief", "heartbreak", "bereavement", "depression after loss", "hiccups", "sore throat"],
    potency: { acute: "200C once", chronic: "1M infrequently" },
    sensations: ["lump throat", "trembling", "heaviness"],
  },
  {
    id: "ip", name: "Ipecacuanha", abbr: "Ip.",
    keynotes: ["persistent nausea not better by vomiting", "bright red hemorrhage", "clean tongue", "no thirst", "cough with nausea"],
    affinities: ["digestive", "respiratory", "blood", "nerves"],
    mentals: ["irritable", "contemptuous", "nothing pleases"],
    modalities: { better: ["open air", "rest", "cold drinks"], worse: ["overeating", "rich food", "warmth", "lying down"] },
    constitution: ["neutral"],
    conditions: ["nausea", "morning sickness", "asthma", "cough", "hemorrhage", "whooping cough"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["nausea constant", "bleeding bright red"],
  },
  {
    id: "kali-bi", name: "Kali Bichromicum", abbr: "Kali-bi.",
    keynotes: ["stringy sticky discharges", "sinusitis", "pressure at root of nose", "round ulcers", "wandering pains"],
    affinities: ["mucous membranes", "sinuses", "digestive", "joints"],
    mentals: ["routine loving", "practical"],
    modalities: { better: ["heat", "motion"], worse: ["cold", "damp", "beer", "2-3am"] },
    constitution: ["chilly"],
    conditions: ["sinusitis", "catarrh", "peptic ulcers", "joint pain", "croup", "migraine"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["pressure", "fullness", "stringy"],
  },
  {
    id: "kali-c", name: "Kali Carbonicum", abbr: "Kali-c.",
    keynotes: ["3am aggravation", "bag-like swelling upper eyelids", "stitching pains", "weakness", "rigid duty-bound"],
    affinities: ["lungs", "kidneys", "heart", "back"],
    mentals: ["duty-bound", "rigid", "fear of being alone", "anxiety in stomach", "irritable"],
    modalities: { better: ["daytime", "warmth", "sitting bent forward"], worse: ["3am", "cold", "drafts", "lying on left"] },
    constitution: ["chilly"],
    conditions: ["asthma 3am", "pneumonia", "back pain", "kidney disease", "cardiac weakness"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["stitching", "weakness", "heaviness"],
  },
  {
    id: "kali-p", name: "Kali Phosphoricum", abbr: "Kali-p.",
    keynotes: ["nerve exhaustion", "exam brain fag", "weakness from overwork", "yellow discharges", "offensive"],
    affinities: ["nervous system", "brain", "blood"],
    mentals: ["nervous exhaustion", "oversensitive", "depressed from overwork", "brain fag"],
    modalities: { better: ["warmth", "rest", "nourishment"], worse: ["excitement", "cold", "noise", "mental exertion"] },
    constitution: ["chilly"],
    conditions: ["nervous exhaustion", "neurasthenia", "exam stress", "depression from overwork", "insomnia nervous"],
    potency: { acute: "6X tissue salt", chronic: "30C daily" },
    sensations: ["weakness", "exhaustion", "nervousness"],
  },
  {
    id: "lach", name: "Lachesis Mutus", abbr: "Lach.",
    keynotes: ["loquacious", "cannot bear constriction", "left sided", "worse after sleep", "jealousy", "menopausal", "bluish"],
    affinities: ["heart", "circulation", "left side", "throat", "blood"],
    mentals: ["talkative", "jealous", "suspicious", "religious", "vivid dreams", "competitive"],
    modalities: { better: ["open air", "cold drinks", "discharges", "appearance of menses"], worse: ["sleep", "constriction", "heat", "left side", "suppressed discharges"] },
    constitution: ["hot"],
    conditions: ["menopause", "sore throat left", "heart disease", "varicose veins", "hemorrhage", "sepsis", "jealousy"],
    potency: { acute: "30C", chronic: "200C or 1M monthly" },
    sensations: ["constriction", "blueness", "throbbing"],
  },
  {
    id: "led", name: "Ledum Palustre", abbr: "Led.",
    keynotes: ["puncture wounds", "cold applications better", "ascending rheumatism", "black eye", "insect bites"],
    affinities: ["joints", "skin", "eyes"],
    mentals: ["indignant", "cross", "misanthropic"],
    modalities: { better: ["cold applications", "cold bathing"], worse: ["warmth", "warmth of bed", "night", "motion"] },
    constitution: ["chilly"],
    conditions: ["puncture wounds", "insect stings", "gout", "rheumatism ascending", "black eye", "tetanus prevention"],
    potency: { acute: "30C every 4hrs", chronic: "200C" },
    sensations: ["coldness", "prickling", "shooting"],
  },
  {
    id: "lyc", name: "Lycopodium Clavatum", abbr: "Lyc.",
    keynotes: ["anticipatory anxiety but copes well", "cowardly", "right sided", "4-8pm worse", "gas flatulence", "craves sweets", "domineering at home"],
    affinities: ["liver", "digestive", "kidneys", "right side"],
    mentals: ["cowardly", "lacks confidence in private", "domineering at home", "fear of responsibility", "craves approval"],
    modalities: { better: ["warm food", "motion", "after midnight", "urinating"], worse: ["4-8pm", "right side", "pressure clothes", "oysters", "cold food"] },
    constitution: ["chilly"],
    conditions: ["digestive complaints", "liver", "kidney stones", "hair loss", "sore throat right", "anxiety performance", "prostate"],
    potency: { acute: "30C", chronic: "200C or 1M monthly" },
    sensations: ["bloating", "fullness", "right-sided"],
  },
  {
    id: "merc", name: "Mercurius Solubilis", abbr: "Merc.",
    keynotes: ["profuse offensive sweat", "salivation", "trembling", "thermometer-like instability", "worse at night", "ulcers with raised edges"],
    affinities: ["mucous membranes", "glands", "skin", "bones", "saliva"],
    mentals: ["slow answer", "unstable", "suspicious", "hasty", "memory weak"],
    modalities: { better: ["moderate temperature", "rest"], worse: ["night", "wet weather", "sweating", "both heat and cold"] },
    constitution: ["neutral"],
    conditions: ["sore throat ulcers", "gum disease", "sinusitis", "dysentery", "liver", "gonorrhea-type discharges"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["trembling", "offensive", "salivation"],
  },
  {
    id: "merc-c", name: "Mercurius Corrosivus", abbr: "Merc-c.",
    keynotes: ["tenesmus never get done", "burning hot urine drops", "intense inflammation", "shreddy stools"],
    affinities: ["mucous membranes", "urinary", "rectum"],
    mentals: ["as merc but more intense"],
    modalities: { better: ["rest"], worse: ["night", "urination", "tenesmus"] },
    constitution: ["neutral"],
    conditions: ["dysentery severe", "cystitis intense", "urethritis", "gonorrhea acute"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["burning", "tenesmus", "shredding"],
  },
  {
    id: "mez", name: "Mezereum", abbr: "Mez.",
    keynotes: ["skin eruptions with thick crusts", "neuralgia after shingles", "bone pains deep", "violent itching better cold"],
    affinities: ["skin", "bones", "nervous system"],
    mentals: ["anxiety in chest", "anxious restless", "religious"],
    modalities: { better: ["open air", "cold"], worse: ["warmth of bed", "cold air on skin", "touch", "night"] },
    constitution: ["chilly"],
    conditions: ["shingles post-herpetic neuralgia", "eczema", "bone pain", "dental neuralgia", "psoriasis thick crust"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["burning", "itching violent", "bone deep pain"],
  },
  {
    id: "nat-m", name: "Natrum Muriaticum", abbr: "Nat-m.",
    keynotes: ["closed grief", "craves salt", "worse consolation", "cold sores", "headache 10am", "reserved hides crying"],
    affinities: ["mucous membranes", "skin", "kidneys", "nervous system"],
    mentals: ["introverted", "grief held inside", "cannot cry when consoled", "romantic past grief", "holds grudges"],
    modalities: { better: ["open air", "cold bathing", "going without regular meals"], worse: ["heat", "10-11am", "consolation", "salt", "seashore"] },
    constitution: ["neutral"],
    conditions: ["migraine 10am", "herpes", "hay fever", "depression grief", "eczema", "thyroid", "irregular menses"],
    potency: { acute: "30C", chronic: "200C or 1M infrequently" },
    sensations: ["dryness", "throbbing", "numbness"],
  },
  {
    id: "nat-p", name: "Natrum Phosphoricum", abbr: "Nat-p.",
    keynotes: ["acidity", "yellow creamy discharges", "worms", "sour vomiting", "flatulence sour"],
    affinities: ["digestive", "joints", "kidneys"],
    mentals: ["oversensitive", "fearful"],
    modalities: { better: ["cold", "open air"], worse: ["fatty food", "sugar", "milk"] },
    constitution: ["neutral"],
    conditions: ["GERD", "worms", "acidity", "rheumatism from acid", "jaundice"],
    potency: { acute: "6X tissue salt", chronic: "30C" },
    sensations: ["sour", "acidity", "burning"],
  },
  {
    id: "nit-ac", name: "Nitricum Acidum", abbr: "Nit-ac.",
    keynotes: ["splinter-like pains", "offensive discharges", "warts fissures", "chilly but worse heat", "unforgiving"],
    affinities: ["mucous membranes", "orifices", "skin", "bones"],
    mentals: ["unforgiving", "vindictive", "anxiety health", "hopeless"],
    modalities: { better: ["riding in carriage", "steady pressure"], worse: ["cold", "heat", "night", "jarring", "touch"] },
    constitution: ["chilly"],
    conditions: ["anal fissures", "warts", "ulcers orifices", "bone pain", "offensive sweating feet"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["splinter", "stinging", "offensive"],
  },
  {
    id: "nux-v", name: "Nux Vomica", abbr: "Nux-v.",
    keynotes: ["oversensitive", "chilly", "irritable", "sedentary over-indulgence", "ineffectual urge", "wakes 3am"],
    affinities: ["digestive", "nervous system", "liver", "spinal cord"],
    mentals: ["irritable", "driven", "cannot tolerate contradiction", "workaholic", "competitive", "hypersensitive"],
    modalities: { better: ["warmth", "damp weather", "nap", "strong pressure"], worse: ["early morning", "cold", "uncovering", "spices", "stimulants"] },
    constitution: ["chilly"],
    conditions: ["hangover", "constipation", "IBS", "headache morning", "insomnia 3am", "nausea digestive", "back pain"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["cramping", "tenesmus", "hypersensitivity"],
  },
  {
    id: "petr", name: "Petroleum", abbr: "Petr.",
    keynotes: ["skin cracks in winter", "motion sickness better eating", "must eat when nauseous", "skin rough thick"],
    affinities: ["skin", "gastric", "nervous system"],
    mentals: ["irritable", "sensitive to noise", "feels double"],
    modalities: { better: ["warm air", "dry weather", "eating"], worse: ["winter", "cold", "damp", "motion", "fasting"] },
    constitution: ["chilly"],
    conditions: ["eczema winter", "fissures", "motion sickness eating better", "gastritis", "labyrinthitis"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["rawness", "roughness", "cracks"],
  },
  {
    id: "phos", name: "Phosphorus", abbr: "Phos.",
    keynotes: ["burning pains", "thirst for cold drinks", "hemorrhage bright red", "tall slender", "sympathetic", "fearful of thunderstorm"],
    affinities: ["lungs", "nerves", "blood vessels", "liver"],
    mentals: ["sympathetic", "fears dark storms being alone", "desires company", "affectionate", "artistic"],
    modalities: { better: ["cold food", "cold drinks", "rubbing", "company", "sleep"], worse: ["twilight", "thunderstorm", "lying on left", "warm food", "salt"] },
    constitution: ["hot"],
    conditions: ["pneumonia", "hepatitis", "hemorrhage", "anxiety", "neuropathy", "cough tickling", "laryngitis"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["burning", "weakness", "hemorrhage"],
  },
  {
    id: "phyt", name: "Phytolacca Decandra", abbr: "Phyt.",
    keynotes: ["throat pain radiates to ear", "hard glands", "shooting pains", "breast affinity", "irresistible desire to bite teeth"],
    affinities: ["throat", "glands", "breasts", "bones", "muscles"],
    mentals: ["indifference", "fear of death", "reckless"],
    modalities: { better: ["dry weather", "warmth", "rest"], worse: ["cold damp", "swallowing", "right side", "night"] },
    constitution: ["chilly"],
    conditions: ["mastitis", "tonsillitis", "glandular fever", "rheumatism shooting", "breast cancer support"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["shooting", "hardness", "radiation"],
  },
  {
    id: "puls", name: "Pulsatilla Pratensis", abbr: "Puls.",
    keynotes: ["changeable symptoms", "weeps easily", "thirstless", "better open air", "desires comfort", "mild yielding"],
    affinities: ["mucous membranes", "venous system", "hormonal", "emotional"],
    mentals: ["weeps easily", "mild", "gentle", "changeable moods", "desires company", "fear of abandonment"],
    modalities: { better: ["open air", "cold", "cold applications", "walking", "company"], worse: ["warmth", "warm room", "fat food", "evening", "left side"] },
    constitution: ["hot"],
    conditions: ["colds with thick discharge", "ear infections", "hormonal issues", "PMS", "depression after childbirth", "digestive from fat"],
    potency: { acute: "30C", chronic: "200C or 1M" },
    sensations: ["changeability", "fullness", "heaviness"],
  },
  {
    id: "rhus-t", name: "Rhus Toxicodendron", abbr: "Rhus-t.",
    keynotes: ["restlessness better motion", "stiffness on first motion", "initial motion painful then eases", "red triangle tip of tongue", "skin vesicular"],
    affinities: ["joints", "skin", "tendons", "fever"],
    mentals: ["restless", "anxious at night", "mild delirium", "suicidal thoughts from water"],
    modalities: { better: ["motion", "warm applications", "hot bath", "dry weather"], worse: ["rest", "cold damp", "first motion", "night", "overexertion"] },
    constitution: ["chilly"],
    conditions: ["arthritis", "rheumatism", "shingles", "eczema vesicular", "influenza", "sprains", "bursitis"],
    potency: { acute: "30C every 4hrs", chronic: "200C weekly" },
    sensations: ["stiffness", "restlessness", "burning vesicular"],
  },
  {
    id: "ruta", name: "Ruta Graveolens", abbr: "Ruta.",
    keynotes: ["injury periosteum", "eye strain", "tendon sheaths", "bruised lame feeling after injury", "wrist injuries"],
    affinities: ["bones periosteum", "tendons", "eyes", "wrists"],
    mentals: ["discontented", "quarrelsome"],
    modalities: { better: ["warmth", "motion"], worse: ["cold damp", "lying", "overexertion"] },
    constitution: ["chilly"],
    conditions: ["periosteal injury", "carpal tunnel", "tennis elbow", "eye strain screens", "ganglion", "sprains tendons"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["lame", "sore", "aching periosteum"],
  },
  {
    id: "sep", name: "Sepia Officinalis", abbr: "Sep.",
    keynotes: ["indifference to loved ones", "worn out bearing down", "loves dancing", "worse consolation", "hormonal", "yellow saddle on nose"],
    affinities: ["uterus", "liver", "veins", "skin"],
    mentals: ["indifferent", "weeps but hates consolation", "resentful", "better dancing or exercise", "flat affect"],
    modalities: { better: ["vigorous exercise", "dancing", "warmth", "cold drinks", "eating"], worse: ["consolation", "sex", "cold", "before menses", "afternoon"] },
    constitution: ["chilly"],
    conditions: ["hormonal imbalance", "PMS", "menopause", "prolapse", "depression post-natal", "liver spots", "herpes"],
    potency: { acute: "200C", chronic: "1M monthly" },
    sensations: ["bearing down", "emptiness", "indifference"],
  },
  {
    id: "sil", name: "Silicea", abbr: "Sil.",
    keynotes: ["lack of confidence", "pushes out foreign bodies", "offensive foot sweat", "chilly", "obstinate when pushed", "migraine from occiput to eye"],
    affinities: ["bones", "glands", "skin", "nervous system"],
    mentals: ["lack confidence", "yielding yet fixed on ideas", "perfectionist", "fear of pins needles failure"],
    modalities: { better: ["warmth", "wrapping head", "summer"], worse: ["cold", "damp", "draft", "uncovering", "new moon", "milk"] },
    constitution: ["chilly"],
    conditions: ["recurrent infections", "abscess", "sinusitis chronic", "warts", "bone fistula", "migraine occipital", "sweating feet"],
    potency: { acute: "30C", chronic: "200C or 1M monthly" },
    sensations: ["splinter", "offensiveness", "weakness"],
  },
  {
    id: "spig", name: "Spigelia Anthelmia", abbr: "Spig.",
    keynotes: ["left-sided headache into eye", "palpitations visible", "neuralgia severe", "fear of pins", "stiff neck"],
    affinities: ["heart", "left side", "eyes", "nervous system"],
    mentals: ["anxiety about needles", "violent temper", "depression"],
    modalities: { better: ["lying on right side", "sunset"], worse: ["motion", "noise", "touch", "morning", "smoking"] },
    constitution: ["chilly"],
    conditions: ["left-sided migraine", "heart palpitations", "trigeminal neuralgia", "eye pain", "worms"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["stinging", "left-sided severe", "pulsating"],
  },
  {
    id: "spong", name: "Spongia Tosta", abbr: "Spong.",
    keynotes: ["dry croupy cough", "saw-through wood sound", "wakes frightened", "better eating and drinking", "thyroid"],
    affinities: ["larynx", "thyroid", "heart", "respiratory"],
    mentals: ["anxiety fear of death", "wakes frightened"],
    modalities: { better: ["eating", "drinking warm", "lying with head low"], worse: ["before midnight", "cold air", "inspiration"] },
    constitution: ["neutral"],
    conditions: ["croup", "croupy cough", "hyperthyroid", "heart disease valvular", "orchitis"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["dry", "hollow", "constriction"],
  },
  {
    id: "staph", name: "Staphysagria", abbr: "Staph.",
    keynotes: ["suppressed anger", "after humiliation", "cystitis after sex", "sweet-natured appears", "romantic sensitive"],
    affinities: ["urinary", "nervous system", "skin", "genital"],
    mentals: ["suppressed indignation", "cannot express anger", "romantic oversensitive", "shame"],
    modalities: { better: ["warmth", "rest", "breakfast"], worse: ["suppressed emotions", "sexual excess", "tobacco", "indignation"] },
    constitution: ["chilly"],
    conditions: ["honeymoon cystitis", "postoperative pain", "styes", "eczema from suppression", "anger illness"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["cutting", "stinging", "pressure"],
  },
  {
    id: "sulph", name: "Sulphur", abbr: "Sulph.",
    keynotes: ["burning heat", "offensive", "worse from washing", "skin eruptions itching burning", "philosopher ragged", "hungry 11am", "hot feet out of bed"],
    affinities: ["skin", "liver", "digestive", "veins"],
    mentals: ["philosophical", "egotistical", "untidy", "critical of others", "burning ideas", "greedy"],
    modalities: { better: ["dry warm weather", "drawing up limbs", "motion"], worse: ["standing", "washing", "11am", "warmth of bed", "wool"] },
    constitution: ["hot"],
    conditions: ["skin diseases", "eczema burning", "digestive disorders", "hepatitis", "hemorrhoids", "relapsing illness"],
    potency: { acute: "30C", chronic: "200C or 1M" },
    sensations: ["burning", "itching", "heat"],
  },
  {
    id: "symph", name: "Symphytum Officinale", abbr: "Symph.",
    keynotes: ["bone fracture healing", "eye injury", "periosteal injury", "non-union fractures"],
    affinities: ["bones", "periosteum", "eyes"],
    mentals: ["irritable"],
    modalities: { better: ["warmth"], worse: ["touch", "injury"] },
    constitution: ["neutral"],
    conditions: ["fractures", "eye trauma blunt", "periosteal wounds", "bone pain", "tennis elbow bone"],
    potency: { acute: "30C daily after fracture", chronic: "6C for healing" },
    sensations: ["aching", "sore periosteum"],
  },
  {
    id: "tab", name: "Tabacum", abbr: "Tab.",
    keynotes: ["sea sickness", "deathly nausea", "cold sweat", "pallor", "vertigo with nausea"],
    affinities: ["nervous system", "stomach", "circulation"],
    mentals: ["hopeless", "spiteful"],
    modalities: { better: ["uncovering", "cold fresh air", "closing eyes"], worse: ["tobacco smell", "motion", "heat"] },
    constitution: ["chilly"],
    conditions: ["sea sickness", "nausea extreme", "vertigo", "angina", "Meniere's"],
    potency: { acute: "30C every 30min", chronic: "200C" },
    sensations: ["deathly nausea", "cold sweat", "pallor"],
  },
  {
    id: "thuj", name: "Thuja Occidentalis", abbr: "Thuj.",
    keynotes: ["warts", "fixed ideas body ugly", "secretive", "vaccination effects", "left-sided", "onion-like odor sweat"],
    affinities: ["skin", "urogenital", "glands", "left side"],
    mentals: ["secretive", "body image distorted", "fixed ideas", "feels made of glass"],
    modalities: { better: ["sneezing", "left side", "warmth"], worse: ["cold damp", "right side", "3am and 3pm", "onions", "vaccination"] },
    constitution: ["chilly"],
    conditions: ["warts all types", "condylomata", "vaccine side effects", "urethral stricture", "sinusitis left", "gonorrhea chronic"],
    potency: { acute: "30C", chronic: "200C or 1M" },
    sensations: ["warty growths", "fixed", "left-sided"],
  },
  {
    id: "verat", name: "Veratrum Album", abbr: "Verat.",
    keynotes: ["collapse cold sweat", "violent vomiting diarrhea", "cold perspiration forehead", "icy cold body", "craves cold drinks"],
    affinities: ["digestive", "heart", "circulation", "nervous system"],
    mentals: ["delirium", "religious mania", "lies curled up", "ambitious delusions of grandeur"],
    modalities: { better: ["warmth", "covered", "walking"], worse: ["wet cold", "drinking", "fright", "exertion"] },
    constitution: ["chilly"],
    conditions: ["cholera", "gastroenteritis severe", "fainting", "collapse", "cramps with vomiting"],
    potency: { acute: "30C every 30min", chronic: "200C" },
    sensations: ["icy cold", "collapse", "violent"],
  },
  {
    id: "zinc", name: "Zincum Metallicum", abbr: "Zinc.",
    keynotes: ["restless legs", "brain fatigue", "cannot finish eruptions", "fidgety feet", "suppressed symptoms", "exhausted nervous"],
    affinities: ["nervous system", "spinal cord", "brain"],
    mentals: ["brain fog", "cannot think", "memory weak", "repeats questions"],
    modalities: { better: ["motion", "appearance of discharge"], worse: ["wine", "touch", "suppressed eruptions", "noise"] },
    constitution: ["chilly"],
    conditions: ["restless legs", "nervous exhaustion", "brain fag", "epilepsy", "convulsions from suppression"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["restlessness", "weakness", "twitching"],
  },
  // ---- remedies 61-100 ----
  {
    id: "ambr", name: "Ambra Grisea", abbr: "Ambr.",
    keynotes: ["extreme embarrassment", "cannot perform before others", "music unbearable", "old age complaints"],
    affinities: ["nervous system", "mind"],
    mentals: ["extreme shyness", "bashful", "cannot open bowels if others in house"],
    modalities: { better: ["slow motion", "open air"], worse: ["company", "music", "conversation"] },
    constitution: ["chilly"],
    conditions: ["bashful bowel", "palpitations before strangers", "insomnia elderly", "nervous conditions"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["embarrassment", "numbness", "palpitation"],
  },
  {
    id: "anac", name: "Anacardium Orientale", abbr: "Anac.",
    keynotes: ["two wills", "feels two opposing forces", "cruelty", "memory weak", "empty feeling better eating"],
    affinities: ["nervous system", "digestive", "mind"],
    mentals: ["two opposing forces", "impulse to curse", "cruelty", "low self-esteem", "fixed ideas"],
    modalities: { better: ["eating", "lying down"], worse: ["fasting", "mental exertion", "hot applications"] },
    constitution: ["neutral"],
    conditions: ["exam stress memory", "gastric ulcers better eating", "mental exhaustion", "split personality"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["empty better eating", "band sensation", "two wills"],
  },
  {
    id: "ant-t", name: "Antimonium Tartaricum", abbr: "Ant-t.",
    keynotes: ["rattling chest mucus", "cannot expectorate", "drowsy pale", "craves acids apples", "cold sweat"],
    affinities: ["lungs", "stomach", "nervous system"],
    mentals: ["despairing", "whining", "fear of being alone", "angry at least thing"],
    modalities: { better: ["sitting erect", "eructation", "expectoration"], worse: ["warmth", "damp", "lying down", "evening"] },
    constitution: ["chilly"],
    conditions: ["bronchitis with rattle", "pneumonia elderly", "asthma mucus", "whooping cough late stage"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["rattling", "suffocation", "drowsiness"],
  },
  {
    id: "aur", name: "Aurum Metallicum", abbr: "Aur.",
    keynotes: ["depression profound", "suicidal", "duty-bound", "bone pains", "heart disease", "self-reproach"],
    affinities: ["heart", "bones", "sinuses", "mind"],
    mentals: ["suicidal", "deep depression", "failure feeling", "self-reproach", "hopeless"],
    modalities: { better: ["music", "warmth", "motion", "open air"], worse: ["cold", "emotional upset", "night", "mental exertion"] },
    constitution: ["chilly"],
    conditions: ["severe depression", "suicidal ideation", "cardiac disease", "bone pain", "sinusitis", "hypertension"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["despair", "heavy heart", "bone pain"],
  },
  {
    id: "bapt", name: "Baptisia Tinctoria", abbr: "Bapt.",
    keynotes: ["rapid sepsis", "bed feels too hard", "body feels scattered", "putrid discharges", "stupor"],
    affinities: ["blood", "digestive", "lungs"],
    mentals: ["stupor", "confusion", "falls asleep mid-sentence", "thinks body parts separate"],
    modalities: { better: ["open air"], worse: ["humidity", "fog", "indoors"] },
    constitution: ["neutral"],
    conditions: ["septicemia", "typhoid fever", "influenza putrid", "tonsillitis septic"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["putrid", "bruised", "scattered"],
  },
  {
    id: "bor", name: "Borax", abbr: "Bor.",
    keynotes: ["fear downward motion", "startles easily", "aphthae mouth", "nervous sensitive infants"],
    affinities: ["mucous membranes", "mind", "skin"],
    mentals: ["fear of downward motion", "startles from noise", "nervous", "anxious"],
    modalities: { better: ["pressure", "evening"], worse: ["downward motion", "noise", "smoking", "cold"] },
    constitution: ["chilly"],
    conditions: ["mouth ulcers", "fear of elevators", "travel fear downward", "infant colic with aphthae"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["aphthae", "fear downward"],
  },
  {
    id: "calend", name: "Calendula Officinalis", abbr: "Calend.",
    keynotes: ["wound healing", "raw open wounds", "prevents suppuration", "surgical wounds", "antiseptic"],
    affinities: ["skin", "wounds", "mucous membranes"],
    mentals: ["irritable"],
    modalities: { better: ["warmth", "walking", "eating"], worse: ["damp", "cloudy weather"] },
    constitution: ["neutral"],
    conditions: ["cuts lacerations", "burns", "surgical wounds", "ulcers", "childbirth perineum", "ear discharge"],
    potency: { acute: "30C / topical tincture", chronic: "30C daily" },
    sensations: ["rawness", "healing"],
  },
  {
    id: "cina", name: "Cina", abbr: "Cina.",
    keynotes: ["worm complaints", "cross irritable children", "bores nose", "grinding teeth", "cannot be touched"],
    affinities: ["digestive", "nervous system"],
    mentals: ["cross", "screams at night", "bores nose", "strikes caretakers"],
    modalities: { better: ["lying on stomach"], worse: ["touch", "worms", "night"] },
    constitution: ["neutral"],
    conditions: ["worm infestation", "irritable cross children", "convulsions from worms", "teeth grinding", "colic worms"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["itching nose anus", "irritability"],
  },
  {
    id: "con", name: "Conium Maculatum", abbr: "Con.",
    keynotes: ["ascending paralysis", "dizziness from turning head", "induration of glands", "grief from celibacy", "staggers"],
    affinities: ["nervous system", "glands", "sexual organs", "breasts"],
    mentals: ["indifference", "memory weakness", "embittered", "grief from sexual abstinence"],
    modalities: { better: ["motion", "pressure", "fasting"], worse: ["lying down", "celibacy", "turning head", "cold"] },
    constitution: ["chilly"],
    conditions: ["breast tumors", "prostate issues", "vertigo", "paralysis", "nerve degeneration"],
    potency: { acute: "30C", chronic: "200C monthly" },
    sensations: ["numbness", "paralytic", "hardness"],
  },
  {
    id: "eupat-p", name: "Eupatorium Perfoliatum", abbr: "Eup-p.",
    keynotes: ["bone breaking pain", "influenza", "thirst for cold water", "vomiting bile during chill"],
    affinities: ["bones", "fever", "respiratory"],
    mentals: ["moaning from pain"],
    modalities: { better: ["sweating", "vomiting"], worse: ["periodically", "cold air", "motion"] },
    constitution: ["neutral"],
    conditions: ["influenza bone pain", "dengue-like", "malaria bone aching", "fever bone pain"],
    potency: { acute: "30C every 3hrs", chronic: "200C" },
    sensations: ["bone breaking", "aching deep"],
  },
  {
    id: "glon", name: "Glonoinum", abbr: "Glon.",
    keynotes: ["congestive headache", "sunstroke", "pulsating bursting head", "cannot bear heat on head", "lost sense of direction"],
    affinities: ["head", "heart", "circulation"],
    mentals: ["confused", "cannot find way home"],
    modalities: { better: ["open air", "cold", "uncovering head"], worse: ["sun", "heat", "bending head backward", "jar"] },
    constitution: ["hot"],
    conditions: ["sunstroke", "migraine congestive", "hypertension crisis", "menopausal flush with headache"],
    potency: { acute: "30C every 30min", chronic: "200C" },
    sensations: ["pulsating", "bursting", "congestive"],
  },
  {
    id: "ham", name: "Hamamelis Virginiana", abbr: "Ham.",
    keynotes: ["venous affinity", "passive dark hemorrhage", "varicose veins sore", "bruised sore feeling"],
    affinities: ["veins", "blood", "mucous membranes"],
    mentals: ["desire to be respected"],
    modalities: { better: ["rest"], worse: ["warm moist air", "motion", "touch", "pressure"] },
    constitution: ["neutral"],
    conditions: ["varicose veins", "hemorrhoids bleeding", "nosebleed passive", "phlebitis", "epistaxis"],
    potency: { acute: "30C / topical", chronic: "200C" },
    sensations: ["soreness veins", "passive bleeding"],
  },
  {
    id: "hyper", name: "Hypericum Perforatum", abbr: "Hyp.",
    keynotes: ["nerve injury pain", "shooting pain along nerves", "crushed fingers toes", "tailbone injury", "puncture with nerve pain"],
    affinities: ["nerves", "spinal cord", "fingers toes"],
    mentals: ["depression post-injury"],
    modalities: { better: ["lying on face", "bending head backward"], worse: ["cold damp", "touch", "concussion"] },
    constitution: ["neutral"],
    conditions: ["nerve injuries", "dental neuralgia", "tailbone injury", "crushed fingertips", "lacerations rich in nerves"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["shooting along nerve", "tingling", "burning"],
  },
  {
    id: "ign2", name: "Ignatia Amara (chronic)", abbr: "Ign.",
    keynotes: ["grief chronic", "sighing repeated", "contradictory symptoms", "hysterical"],
    affinities: ["mind", "nervous system"],
    mentals: ["chronic grief", "contradictions", "hysterical"],
    modalities: { better: ["eating", "pressure"], worse: ["coffee", "emotions"] },
    constitution: ["neutral"],
    conditions: ["chronic grief states", "hysteria", "depression from loss"],
    potency: { acute: "200C", chronic: "1M" },
    sensations: ["lump", "sighing", "hollow"],
  },
  {
    id: "kali-br", name: "Kali Bromatum", abbr: "Kali-br.",
    keynotes: ["acne", "restlessness hands", "fidgety", "guilt feelings", "memory loss"],
    affinities: ["nervous system", "skin", "sexual organs"],
    mentals: ["guilty", "religious despair", "memory loss", "fidgety hands"],
    modalities: { better: ["occupation"], worse: ["night", "guilt"] },
    constitution: ["chilly"],
    conditions: ["acne", "epilepsy", "insomnia", "sexual excess disorders"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["numbness", "itching"],
  },
  {
    id: "lob", name: "Lobelia Inflata", abbr: "Lob.",
    keynotes: ["nausea with profuse salivation", "asthma with nausea", "weakness pit of stomach", "tobacco abuse"],
    affinities: ["respiratory", "stomach", "nervous system"],
    mentals: ["fear of death from disease"],
    modalities: { better: ["rapid walking", "eating small"], worse: ["tobacco", "cold", "pregnancy"] },
    constitution: ["neutral"],
    conditions: ["asthma with gastric nausea", "morning sickness severe", "tobacco effects"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["nausea weakness stomach", "suffocation"],
  },
  {
    id: "med", name: "Medorrhinum", abbr: "Med.",
    keynotes: ["intense state", "hurry sense of urgency", "craves salt fat ice cream", "worse daytime better at sea"],
    affinities: ["mucous membranes", "joints", "mind", "sexual organs"],
    mentals: ["intense", "feels time slows", "forgetful words", "hurried"],
    modalities: { better: ["sea", "lying on stomach", "night"], worse: ["daylight", "sunrise to sunset", "heat"] },
    constitution: ["hot"],
    conditions: ["gonorrhea history", "pelvic inflammation", "asthma worse daytime", "warts condylomata"],
    potency: { acute: "200C", chronic: "1M infrequently" },
    sensations: ["intense urgency", "hurry", "burning"],
  },
  {
    id: "naja", name: "Naja Tripudians", abbr: "Naja.",
    keynotes: ["heart disease left side", "conscience issues", "hatred", "post-diphtheria heart", "profound sadness"],
    affinities: ["heart", "nervous system", "left side"],
    mentals: ["conscience guilt", "suicidal from guilt", "hatred of others", "profound sadness"],
    modalities: { better: ["walking", "open air"], worse: ["sleep", "cold", "exertion"] },
    constitution: ["chilly"],
    conditions: ["cardiac after viral illness", "post-COVID heart", "depression with guilt", "angina left"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["cardiac heaviness", "constriction"],
  },
  {
    id: "nat-c", name: "Natrum Carbonicum", abbr: "Nat-c.",
    keynotes: ["sun aggravates", "weakness from heat", "selfless service", "aversion to certain people", "milk intolerance"],
    affinities: ["nervous system", "digestive", "mucous membranes"],
    mentals: ["devoted", "selfless", "music melancholy", "anxiety during storm", "aversion to outsiders"],
    modalities: { better: ["eating", "music cheerful", "motion"], worse: ["sun", "heat", "milk", "mental exertion", "storm"] },
    constitution: ["chilly"],
    conditions: ["sunstroke chronic", "milk intolerance", "digestive weakness", "depression post-illness", "ankle weakness"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["weakness", "exhaustion from sun"],
  },
  {
    id: "nat-s", name: "Natrum Sulphuricum", abbr: "Nat-s.",
    keynotes: ["head injury effects", "suicidal reluctant to live", "damp aggravates", "liver affinity morning"],
    affinities: ["liver", "lungs", "mind", "head"],
    mentals: ["suicidal but holds back", "sadness morning", "music affects deeply"],
    modalities: { better: ["open air", "pressure", "changing position"], worse: ["damp weather", "music", "lying on left", "4-5am"] },
    constitution: ["chilly"],
    conditions: ["post-concussion", "head injury effects", "liver disease", "asthma damp", "suicidal"],
    potency: { acute: "200C", chronic: "1M infrequently" },
    sensations: ["heaviness", "damp aggravation"],
  },
  {
    id: "phos-ac", name: "Phosphoricum Acidum", abbr: "Phos-ac.",
    keynotes: ["grief and loss debility", "indifference first then weakness", "growing pains", "hair falls from grief"],
    affinities: ["nervous system", "bones", "mind", "sexual"],
    mentals: ["apathy from grief", "indifference", "cannot collect thoughts"],
    modalities: { better: ["warmth", "short sleep"], worse: ["grief", "loss fluids", "night", "cold"] },
    constitution: ["chilly"],
    conditions: ["post-grief debility", "nervous exhaustion from loss", "growing pains", "hair loss grief"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["weakness", "indifference", "heaviness"],
  },
  {
    id: "plat", name: "Platina", abbr: "Plat.",
    keynotes: ["arrogance", "contempt", "sexual hypersensitivity", "numbness", "ovarian affinity", "haughty"],
    affinities: ["nervous system", "ovaries", "sexual organs", "mind"],
    mentals: ["arrogant", "haughty", "contemptuous", "sexual obsession"],
    modalities: { better: ["open air", "motion"], worse: ["emotions", "touch genitals", "evening"] },
    constitution: ["hot"],
    conditions: ["ovarian cysts", "dysmenorrhea", "nymphomania", "haughty personality"],
    potency: { acute: "200C", chronic: "1M" },
    sensations: ["numbness", "constriction", "oversensitivity"],
  },
  {
    id: "pyrog", name: "Pyrogenium", abbr: "Pyrog.",
    keynotes: ["bed feels too hard like Arnica", "high fever rapid pulse mismatch", "septic states", "offensiveness extreme"],
    affinities: ["blood", "fever", "sepsis"],
    mentals: ["confused identity", "rapid thoughts"],
    modalities: { better: ["heat", "motion", "pressure"], worse: ["cold", "sitting still"] },
    constitution: ["neutral"],
    conditions: ["septicemia", "puerperal fever", "post-surgical infection", "food poisoning septic", "abscess non-healing"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["putrid", "offensive", "restless septic"],
  },
  {
    id: "ran-b", name: "Ranunculus Bulbosus", abbr: "Ran-b.",
    keynotes: ["intercostal neuralgia", "shingles", "pleurisy", "blue black vesicles", "alcohol aggravates"],
    affinities: ["chest", "nerves", "skin"],
    mentals: ["quarrelsome"],
    modalities: { better: ["lying still"], worse: ["motion", "alcohol", "cold air", "change weather"] },
    constitution: ["neutral"],
    conditions: ["shingles intercostal", "pleurisy", "intercostal neuralgia", "corns hands"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["intercostal pain", "burning vesicular"],
  },
  {
    id: "rhod", name: "Rhododendron", abbr: "Rhod.",
    keynotes: ["storm approach aggravates", "orchitis", "rheumatism worse before storm", "right-sided"],
    affinities: ["joints", "testes", "nervous system"],
    mentals: ["forgetful", "confused before storm"],
    modalities: { better: ["warmth", "dry weather", "motion"], worse: ["before storm", "cold wet", "rest", "cold"] },
    constitution: ["chilly"],
    conditions: ["rheumatism storm-related", "orchitis", "gout", "neuralgia"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["tearing", "rheumatic"],
  },
  {
    id: "rob", name: "Robinia Pseudacacia", abbr: "Rob.",
    keynotes: ["acidity extreme", "heartburn worse lying", "vomiting acid", "sour everything"],
    affinities: ["digestive", "stomach"],
    mentals: ["none distinctive"],
    modalities: { better: ["motion"], worse: ["night", "lying", "acid food"] },
    constitution: ["neutral"],
    conditions: ["GERD", "heartburn severe", "acid reflux", "sour vomiting", "child acidity"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["burning acid", "sour"],
  },
  {
    id: "rumex", name: "Rumex Crispus", abbr: "Rumex.",
    keynotes: ["tickling cough from cold air", "covers mouth to breathe warm", "thin watery coryza", "skin itching from cold"],
    affinities: ["respiratory", "skin", "digestive"],
    mentals: ["none distinctive"],
    modalities: { better: ["warm covering mouth", "warmth"], worse: ["cold air", "uncovering", "pressure", "morning"] },
    constitution: ["chilly"],
    conditions: ["dry tickling cough", "chronic bronchitis", "hay fever thin discharge", "itching cold air"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["tickling", "thin watery"],
  },
  {
    id: "sabad", name: "Sabadilla", abbr: "Sabad.",
    keynotes: ["sneezing fits", "hay fever", "violent sneezing", "itching roof of mouth", "delusion of illness"],
    affinities: ["mucous membranes nose", "nerves"],
    mentals: ["hypochondriac", "imagines disease"],
    modalities: { better: ["warm food", "warmth"], worse: ["cold", "flowers", "perfume", "full moon"] },
    constitution: ["chilly"],
    conditions: ["hay fever severe", "sneezing violent", "rhinitis allergic", "hypochondria"],
    potency: { acute: "30C every 2hrs", chronic: "200C" },
    sensations: ["itching nose", "sneezing", "tickling"],
  },
  {
    id: "sang", name: "Sanguinaria Canadensis", abbr: "Sang.",
    keynotes: ["migraine right temple to eye", "burning palms soles", "climacteric complaints", "shoulder right"],
    affinities: ["right side", "lungs", "stomach", "head"],
    mentals: ["irritable", "sees red"],
    modalities: { better: ["sleep", "vomiting", "darkness", "lying down"], worse: ["sun", "right side", "periodically", "smell"] },
    constitution: ["hot"],
    conditions: ["migraine right-sided", "menopause flushes", "right shoulder", "lung ailments", "polyps"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["burning", "throbbing right", "flushing"],
  },
  {
    id: "stram", name: "Stramonium", abbr: "Stram.",
    keynotes: ["terror", "violence", "dark water fear", "alone at night fear", "delirium bright objects"],
    affinities: ["nervous system", "throat", "mind"],
    mentals: ["terror", "violence", "religious mania", "fears dark water alone", "delirium bright"],
    modalities: { better: ["company", "light", "warmth"], worse: ["dark", "alone", "water", "glistening objects"] },
    constitution: ["hot"],
    conditions: ["PTSD", "delirium", "epilepsy", "violent mania", "stuttering"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["violent", "terror", "spasm"],
  },
  {
    id: "tub", name: "Tuberculinum Bovinum", abbr: "Tub.",
    keynotes: ["always wants change", "travel desire intense", "intellectual family TB history", "cats love", "better cold open air"],
    affinities: ["lungs", "glands", "mind", "nervous system"],
    mentals: ["desires change", "restless", "loves animals", "intellectual sensitive"],
    modalities: { better: ["open air", "cold", "traveling"], worse: ["damp cold", "before storm", "exertion"] },
    constitution: ["chilly"],
    conditions: ["recurrent respiratory", "glandular issues", "restless ADHD children", "TB family history"],
    potency: { acute: "200C", chronic: "1M infrequently" },
    sensations: ["restless", "desire change"],
  },
  {
    id: "valer", name: "Valeriana Officinalis", abbr: "Valer.",
    keynotes: ["hysteria", "oversensitive", "sensation of floating", "pain changes place", "nervous temperament"],
    affinities: ["nervous system", "mind"],
    mentals: ["hysterical", "changeable moods", "feels she floats"],
    modalities: { better: ["motion", "warmth"], worse: ["rest", "standing", "cold"] },
    constitution: ["neutral"],
    conditions: ["hysteria", "sciatica better walking", "insomnia nervous", "pain shifting"],
    potency: { acute: "30C", chronic: "200C" },
    sensations: ["floating", "shifting pain", "hysteria"],
  },
  {
    id: "vib", name: "Viburnum Opulus", abbr: "Vib.",
    keynotes: ["spasmodic dysmenorrhea", "cramping uterine", "bearing down before menses", "miscarriage prevention"],
    affinities: ["uterus", "ovaries"],
    mentals: ["irritable premenstrual"],
    modalities: { better: ["warmth", "pressure"], worse: ["cold", "before menses"] },
    constitution: ["neutral"],
    conditions: ["dysmenorrhea", "threatened miscarriage", "ovarian cramps", "premenstrual cramps"],
    potency: { acute: "30C every hour", chronic: "200C" },
    sensations: ["spasm", "bearing down", "cramp"],
  },
];
